STDDEV = 1.1
BUFFER_SIZE = 1000
BATCH_SIZE = 28

PRETRAIN = False
DATASET = "mnist"
assert DATASET in ["mnist", "kmnist", "celeba"]
IMAGESIZES = {
    "mnist": 32,
    "kmnist": 32,
    "celeba": 128
}
IMAGESIZE = IMAGESIZES[DATASET]
NEW_NOISE_EVERY_EPOCH = False
ACF_SCALE_FACTOR = 1
BETA1 = 0.
BETA2 = 0.9
GENERATOR_LR = 2e-5
DISCRIMINATOR_LR = 2e-5
LR_DECAY_RATE = 0.9
DECAY_STEPS = 100000
NOISE_DIMENSION = [64]
NOISE_TYPE = 'GAUSSIAN'
IMG_LOGGING_INTERVAL = 1000
SCALAR_LOGGING_INTERVAL = 200
CHECK_INTRABATCH_ACF = True
LOGDIR = 'logs'
N2N_LOSS_SF = 1
NO_VARIANTS = 10
SMOOTH_MARGIN = 0.25
EPOCHS_NO = 20000
FLIP_LABELS = True
FLIP_PART = 0.05
SPLIT = 'hdn_real'
WASSERSTEIN = False
DIVERSIFY = True
DIVERSIFY_LOSS_MULTIPLIER = 0.08
TIMES_GENERATOR_TRAINED = 1
TIMES_DISCRIMINATOR_TRAINED = 1
if DATASET in ["mnist", "kmnist"]:
    CHANNELS = 1
else:
    CHANNELS = 3
GP_MULTIPLIER = 10
CELEBA_PATH = ''
N2C = True
PRETRAIN_GENERATOR_LR = 5e-05
PRETRAIN_DISCRIMINATOR_LR = 5e-05
PRETRAIN_DISCRIMINATOR_EPOCHS = 20000
MSE_LOSS = True
MSE_LOSS_MULTIPLIER = 2000.
INCREASE_PACK_INTERVAL = 100
CELEBA_LAYER_SCALE_FACTOR = 64
DIV_LOSS_MAX = False
SRGAN_MODELS = False
PACK_FACTORS = False
CELEBA_BOUNDING_BOX = (57, 21, 128, 128)

CHECKPOINTS_DIR = 'checkpoints'
try:
    from local_settings import *
except ImportError:
    pass
